version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 940922024450.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t chhabra-final-api .
      - docker tag chhabra-final-api:latest 940922024450.dkr.ecr.ca-central-1.amazonaws.com/chhabra-final-api:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 940922024450.dkr.ecr.ca-central-1.amazonaws.com/chhabra-final-api:latest

